# -*- coding: utf-8 -*-
"""
/***************************************************************************
 wtyczka_projekt
                                 A QGIS plugin
 Wtyczka pozwalająca na liczenie przewyższenia pomiędzy dwoma punktami oraz pole powierzchni metodą Gaussa
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-10
        copyright            : (C) 2023 by wdef
        email                : julka571@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load wtyczka_projekt class from file wtyczka_projekt.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .wtyczka_pro import wtyczka_projekt
    return wtyczka_projekt(iface)
