# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wtyczka_pro_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wtyczka_projektDialogBase(object):
    def setupUi(self, wtyczka_projektDialogBase):
        wtyczka_projektDialogBase.setObjectName("wtyczka_projektDialogBase")
        wtyczka_projektDialogBase.resize(504, 300)
        self.button_box = QtWidgets.QDialogButtonBox(wtyczka_projektDialogBase)
        self.button_box.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.PB_pole = QtWidgets.QPushButton(wtyczka_projektDialogBase)
        self.PB_pole.setGeometry(QtCore.QRect(280, 170, 93, 28))
        self.PB_pole.setObjectName("PB_pole")
        self.PB_wys = QtWidgets.QPushButton(wtyczka_projektDialogBase)
        self.PB_wys.setGeometry(QtCore.QRect(280, 100, 93, 28))
        self.PB_wys.setObjectName("PB_wys")
        self.layer = QgsMapLayerComboBox(wtyczka_projektDialogBase)
        self.layer.setGeometry(QtCore.QRect(150, 30, 191, 41))
        self.layer.setObjectName("layer")
        self.label_wys = QtWidgets.QLabel(wtyczka_projektDialogBase)
        self.label_wys.setGeometry(QtCore.QRect(390, 100, 81, 31))
        self.label_wys.setText("")
        self.label_wys.setObjectName("label_wys")
        self.label_pole = QtWidgets.QLabel(wtyczka_projektDialogBase)
        self.label_pole.setGeometry(QtCore.QRect(390, 170, 81, 21))
        self.label_pole.setText("")
        self.label_pole.setObjectName("label_pole")
        self.label_wys_2 = QtWidgets.QLabel(wtyczka_projektDialogBase)
        self.label_wys_2.setGeometry(QtCore.QRect(20, 100, 241, 21))
        self.label_wys_2.setObjectName("label_wys_2")
        self.label_wys_3 = QtWidgets.QLabel(wtyczka_projektDialogBase)
        self.label_wys_3.setGeometry(QtCore.QRect(20, 150, 251, 61))
        self.label_wys_3.setObjectName("label_wys_3")

        self.retranslateUi(wtyczka_projektDialogBase)
        self.button_box.accepted.connect(wtyczka_projektDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(wtyczka_projektDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(wtyczka_projektDialogBase)

    def retranslateUi(self, wtyczka_projektDialogBase):
        _translate = QtCore.QCoreApplication.translate
        wtyczka_projektDialogBase.setWindowTitle(_translate("wtyczka_projektDialogBase", "wtyczka_projekt"))
        self.PB_pole.setText(_translate("wtyczka_projektDialogBase", "POLICZ"))
        self.PB_wys.setText(_translate("wtyczka_projektDialogBase", "POLICZ"))
        self.label_wys_2.setText(_translate("wtyczka_projektDialogBase", "KLIKNIJ ABY POLICZYĆ PRZEWYŻSZENIE"))
        self.label_wys_3.setText(_translate("wtyczka_projektDialogBase", "KLIKNIJ ABY POLICZYĆ POLE POWIERZCHNI"))
from qgsmaplayercombobox import QgsMapLayerComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wtyczka_projektDialogBase = QtWidgets.QDialog()
    ui = Ui_wtyczka_projektDialogBase()
    ui.setupUi(wtyczka_projektDialogBase)
    wtyczka_projektDialogBase.show()
    sys.exit(app.exec_())
